import { BusinessCategory } from '../../business/enums/business-category.enum';
import { BusinessMainItem } from '../../business/enums/business-mainitems.enum';

export const CATEGORY_MAIN_ITEMS_MAP: Record<BusinessCategory, BusinessMainItem[]> = {
  [BusinessCategory.STORE]: [
    BusinessMainItem.GROCERIES,
    BusinessMainItem.FRESH_PRODUCE,
    BusinessMainItem.SNACKS,
    BusinessMainItem.BEVERAGES,
    BusinessMainItem.DAIRY_PRODUCTS,
    BusinessMainItem.FROZEN_FOOD,
    BusinessMainItem.CLEANING_SUPPLIES,
    BusinessMainItem.PERSONAL_CARE,
    BusinessMainItem.BABY_PRODUCTS,
    BusinessMainItem.HOUSEHOLD_ESSENTIALS,
    BusinessMainItem.MOBILE_ACCESSORIES,
    BusinessMainItem.ELECTRONICS,
    BusinessMainItem.HEALTH_WELLNESS,
    BusinessMainItem.PET_FOOD,
    BusinessMainItem.BAKERY_ITEMS,
  ],

  [BusinessCategory.RESTAURANT]: [
    BusinessMainItem.SANDWICHES,
    BusinessMainItem.BURGERS,
    BusinessMainItem.GRILLED_ITEMS,
    BusinessMainItem.FRIED_CHICKEN,
    BusinessMainItem.PASTA,
    BusinessMainItem.PIZZA,
    BusinessMainItem.SEAFOOD_PLATES,
    BusinessMainItem.SALADS,
    BusinessMainItem.SIDES,
    BusinessMainItem.BREAKFAST,
    BusinessMainItem.DESSERTS,
    BusinessMainItem.ORIENTAL_DISHES,
    BusinessMainItem.BEVERAGES_MENU,
    BusinessMainItem.SHAWARMA,
    BusinessMainItem.FAMILY_MEALS,
  ],

  [BusinessCategory.CLINIC]: [
    BusinessMainItem.GENERAL_CONSULTATION,
    BusinessMainItem.FOLLOW_UP,
    BusinessMainItem.PEDIATRIC_CHECKUP,
    BusinessMainItem.DERMATOLOGY_SESSION,
    BusinessMainItem.DENTAL_EXAMINATION,
    BusinessMainItem.TEETH_CLEANING,
    BusinessMainItem.DENTAL_FILLING,
    BusinessMainItem.LAB_TESTS,
    BusinessMainItem.BLOOD_ANALYSIS,
    BusinessMainItem.ULTRASOUND,
    BusinessMainItem.PRESCRIPTION_RENEWAL,
    BusinessMainItem.VACCINATIONS,
    BusinessMainItem.EMERGENCY_CASES_CLINIC,
    BusinessMainItem.WOUND_CARE,
    BusinessMainItem.CHRONIC_DISEASE_MANAGEMENT,
  ],

  [BusinessCategory.GYM]: [
    BusinessMainItem.STRENGTH_TRAINING,
    BusinessMainItem.CARDIO_WORKOUTS,
    BusinessMainItem.PERSONAL_TRAINING,
    BusinessMainItem.FITNESS_ASSESSMENT,
    BusinessMainItem.GROUP_CLASSES,
    BusinessMainItem.CROSSFIT,
    BusinessMainItem.HIIT,
    BusinessMainItem.YOGA,
    BusinessMainItem.PILATES,
    BusinessMainItem.ZUMBA,
    BusinessMainItem.SPINNING,
    BusinessMainItem.WEIGHTLIFTING,
    BusinessMainItem.STRETCHING,
    BusinessMainItem.NUTRITION_GUIDANCE,
    BusinessMainItem.WEIGHT_LOSS_PROGRAMS,
  ],

  [BusinessCategory.SERVICE]: [
    BusinessMainItem.HOME_CLEANING,
    BusinessMainItem.DEEP_CLEANING,
    BusinessMainItem.AC_MAINTENANCE,
    BusinessMainItem.PLUMBING_REPAIR,
    BusinessMainItem.ELECTRICAL_WORK,
    BusinessMainItem.APPLIANCE_REPAIR,
    BusinessMainItem.MOBILE_REPAIR,
    BusinessMainItem.CAR_WASH,
    BusinessMainItem.BEAUTY_SERVICES,
    BusinessMainItem.HAIR_STYLING,
    BusinessMainItem.HOME_PAINTING,
    BusinessMainItem.FURNITURE_ASSEMBLY,
    BusinessMainItem.PEST_CONTROL,
    BusinessMainItem.EMERGENCY_REPAIR,
    BusinessMainItem.INSTALLATION_SERVICES,
  ],
};
