export enum BusinessMainItem {
  // STORE
  GROCERIES = 'groceries',
  FRESH_PRODUCE = 'fresh_produce',
  SNACKS = 'snacks',
  BEVERAGES = 'beverages',
  DAIRY_PRODUCTS = 'dairy_products',
  FROZEN_FOOD = 'frozen_food',
  CLEANING_SUPPLIES = 'cleaning_supplies',
  PERSONAL_CARE = 'personal_care',
  BABY_PRODUCTS = 'baby_products',
  HOUSEHOLD_ESSENTIALS = 'household_essentials',
  MOBILE_ACCESSORIES = 'mobile_accessories',
  ELECTRONICS = 'electronics',
  HEALTH_WELLNESS = 'health_wellness',
  PET_FOOD = 'pet_food',
  BAKERY_ITEMS = 'bakery_items',

  // RESTAURANT
  SANDWICHES = 'sandwiches',
  BURGERS = 'burgers',
  GRILLED_ITEMS = 'grilled_items',
  FRIED_CHICKEN = 'fried_chicken',
  PASTA = 'pasta',
  PIZZA = 'pizza',
  SEAFOOD_PLATES = 'seafood_plates',
  SALADS = 'salads',
  SIDES = 'sides',
  BREAKFAST = 'breakfast',
  DESSERTS = 'desserts',
  ORIENTAL_DISHES = 'oriental_dishes',
  BEVERAGES_MENU = 'beverages_menu',
  SHAWARMA = 'shawarma',
  FAMILY_MEALS = 'family_meals',

  // CLINIC
  GENERAL_CONSULTATION = 'general_consultation',
  FOLLOW_UP = 'follow_up',
  PEDIATRIC_CHECKUP = 'pediatric_checkup',
  DERMATOLOGY_SESSION = 'dermatology_session',
  DENTAL_EXAMINATION = 'dental_examination',
  TEETH_CLEANING = 'teeth_cleaning',
  DENTAL_FILLING = 'dental_filling',
  LAB_TESTS = 'lab_tests',
  BLOOD_ANALYSIS = 'blood_analysis',
  ULTRASOUND = 'ultrasound',
  PRESCRIPTION_RENEWAL = 'prescription_renewal',
  VACCINATIONS = 'vaccinations',
  EMERGENCY_CASES_CLINIC = 'emergency_cases_clinic',
  WOUND_CARE = 'wound_care',
  CHRONIC_DISEASE_MANAGEMENT = 'chronic_disease_management',

  // GYM
  STRENGTH_TRAINING = 'strength_training',
  CARDIO_WORKOUTS = 'cardio_workouts',
  PERSONAL_TRAINING = 'personal_training',
  FITNESS_ASSESSMENT = 'fitness_assessment',
  GROUP_CLASSES = 'group_classes',
  CROSSFIT = 'crossfit',
  HIIT = 'hiit',
  YOGA = 'yoga',
  PILATES = 'pilates',
  ZUMBA = 'zumba',
  SPINNING = 'spinning',
  WEIGHTLIFTING = 'weightlifting',
  STRETCHING = 'stretching',
  NUTRITION_GUIDANCE = 'nutrition_guidance',
  WEIGHT_LOSS_PROGRAMS = 'weight_loss_programs',

  // SERVICE
  HOME_CLEANING = 'home_cleaning',
  DEEP_CLEANING = 'deep_cleaning',
  AC_MAINTENANCE = 'ac_maintenance',
  PLUMBING_REPAIR = 'plumbing_repair',
  ELECTRICAL_WORK = 'electrical_work',
  APPLIANCE_REPAIR = 'appliance_repair',
  MOBILE_REPAIR = 'mobile_repair',
  CAR_WASH = 'car_wash',
  BEAUTY_SERVICES = 'beauty_services',
  HAIR_STYLING = 'hair_styling',
  HOME_PAINTING = 'home_painting',
  FURNITURE_ASSEMBLY = 'furniture_assembly',
  PEST_CONTROL = 'pest_control',
  EMERGENCY_REPAIR = 'emergency_repair',
  INSTALLATION_SERVICES = 'installation_services',
}
